### ISSUE TITLE
[Faction][Gnoll] Gnoll band encounter

### ISSUE THREAD

**Issue by warius1983** [datchannin/Brothers-WoW#32]
What to fix:

remove dagger from gnoll assasin

mistyc and poacher, strong ranged attack, normal melee attack,

Control Brtue damage on tanks,

implementation rookie gnolls?

**Comment by warius1983** [comment]
From BB WIKI:
https://battlebrothers.fandom.com/wiki/Combat_Mechanics

I am reading these values and the rules to determine meleedefense and meleeskill of gnolls, watching my brothers

As far as I know

we have the following gnolls

![](https://cdn.discordapp.com/attachments/720587456545685525/764613361103011890/unknown.png)

**Comment by warius1983** [comment]
Gnoll Rookie
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill 

Gnoll 
Meleedef   Meleeskill   rangeddef    rangedskill

**Comment by datchannin** [comment]
you can look values in game file:
scripts\config\faction_gnolls.nut
This file contain all gnoll stats.
For example, this is Gnoll Assassin:

gt.Const.Tactical.Actor.GnollAssassin <- {
	XP = 820,
	ActionPoints = 9,
	Hitpoints = 320,
	Bravery = 110,
	Stamina = 300,
	MeleeSkill = 85,
	RangedSkill = 65,
	MeleeDefense = 25,
	RangedDefense = 15,
	Initiative = 150,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 35,
	DamageTotalMult = 1.05
};

**Comment by warius1983** [comment]
ok I can check them thank you very much

**Comment by warius1983** [comment]
Found all data, I am gonna fill armor values in gnolls.nut, I know it is not the correct way, but at least i have all information together
, forgive me :D

**Comment by warius1983** [comment]
gt.Const.Tactical.Actor.GnollRookie <- {
	XP = 650,
	ActionPoints = 9,
	Hitpoints = 200,
	Bravery = 85,
	Stamina = 160,
	MeleeSkill = 75,
	RangedSkill = 65,
	MeleeDefense = 10,
	RangedDefense = 10,
	Initiative = 120,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 25,
	DamageTotalMult = 1.05
};

gt.Const.Tactical.Actor.GnollMystic <- {
	XP = 720,
	ActionPoints = 12,
	Hitpoints = 250,
	Bravery = 95,
	Stamina = 200,
	MeleeSkill = 50,
	RangedSkill = 50,
	MeleeDefense = 0,
	RangedDefense = 0,
	Initiative = 130,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 35
};
gt.Const.Tactical.Actor.GnollShaman <- {
	XP = 820,
	ActionPoints = 11,
	Hitpoints = 230,
	Bravery = 95,
	Stamina = 200,
	MeleeSkill = 50,
	RangedSkill = 50,
	MeleeDefense = 0,
	RangedDefense = 0,
	Initiative = 130,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 35
};
gt.Const.Tactical.Actor.GnollPoacher <- {
	XP = 780,
	ActionPoints = 9,
	Hitpoints = 250,
	Bravery = 95,
	Stamina = 230,
	MeleeSkill = 60,
	RangedSkill = 90,
	MeleeDefense = 10,
	RangedDefense = 25,
	Initiative = 150,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 35,
	DamageTotalMult = 1.05
};
gt.Const.Tactical.Actor.GnollAssassin <- {
	XP = 820,
	ActionPoints = 9,
	Hitpoints = 320,
	Bravery = 110,
	Stamina = 300,
	MeleeSkill = 85,
	RangedSkill = 65,
	MeleeDefense = 25,
	RangedDefense = 15,
	Initiative = 150,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 35,
	DamageTotalMult = 1.05
};
gt.Const.Tactical.Actor.GnollBrute <- {
	XP = 950,
	ActionPoints = 9,
	Hitpoints = 370,
	Bravery = 150,
	Stamina = 270,
	MeleeSkill = 85,
	RangedSkill = 65,
	MeleeDefense = 15,
	RangedDefense = 15,
	Initiative = 130,
	FatigueEffectMult = 1.0,
	MoraleEffectMult = 1.0,
	Armor = [
		0,
		0
	],
	FatigueRecoveryRate = 35,
	DamageTotalMult = 1.1
};

**Comment by warius1983** [comment]
I have not done yet, i will need to check their weapons

**Comment by warius1983** [comment]
I have seen that you made Gnolls very powerful in attack but rather weak in defense, too much weak, i added some armor and defense to rookie, but lowered a bit the offensive ratings.

I empowered up essentially the rooke gnolls giving them some armor, i beleive gnoll rookie have to wiyhstand some more in field, they need to buy time for greater troops to attack you, so the longer they last the more damage you take from big guys.

Assasins have been really buffed in defense, I did this to kill them in ability/magic way, paladin stun and spells are the best way to deal with them sending melee troops may be not the best idea to face them.

About the Brute i am little in conflict, I need to see them a little bit more in battle before judging, so 15 melee def can go, they have ton of armor and health but they got almost always hit

**Comment by datchannin** [comment]
Daggers were removed.
One-Handed Mace was implemented
Rookies were setup.
Rookies were added to new location.
Need test how difficult for raid new location.

**Comment by warius1983** [comment]
is everything ready?

**Comment by datchannin** [comment]
Close. Gnoll event was finished.
