### ISSUE TITLE
[Item] Taxidermist recipes T0 sets

### ISSUE THREAD

**Issue by warius1983** [datchannin/Brothers-WoW#33]
can you write here the recipes to craft the sets?

**Comment by datchannin** [comment]
I've added receipts already.
You can exchange tier item into set item.
![image](https://user-images.githubusercontent.com/39913306/97788606-4e3f1480-1bcb-11eb-9285-2ffc16fd49da.png)

**Comment by warius1983** [comment]
so for now it is only reuired one token to craft them?

so token are the same for all the classes and 1 token only is required + gold?

**Comment by warius1983** [comment]
I'd say for example every champion drops a tier shard, so you roam around the world and drop them, when you have killed some champions you will have some of them.

Since farming in this way can be pretty easy I'd say 20 shards can be crafted in a chest token, 15 shards in helm token, and 10 shards in shoulders token, and gnoll can drop the token it self

**Comment by warius1983** [comment]
Ok I think those money are just numbers.

If we consider the tier as the best avaiable armor for each class, maybe the price to convert shars to token should be around 15-20k gold, and token to tier around yes 2-5k, afterall the pure token is pretty nasty to get, what do you say wanna create this shard piece? it could be useful in future

**Comment by datchannin** [comment]
Now I created tokens, without shards. Token can be looted from gnoll location.
One token = one item.
Shoulder token can be changed into shoulder item. The same token for all 8 items.
Armor token into armor item, helmet - into helmet item.

Shards idea is the same as you describe - change several 15/20 shards into token. Then change token into item.
I think shard can be looted from all types af locations (undead, barbarian, raider, orc and goblin, south) with lower chance. May be 5-10%. So you can farm all locations one by one and try get as many shards as you can.

Gold now is just as example. Number should be updated.

**Comment by warius1983** [comment]
perfect in theory we agree on the subkkects, just number to be confirmed

**Comment by warius1983** [comment]
you know if mods thad add recipes on taxidermist give conflicts? theorically no because I used some of them, but i will try

**Comment by datchannin** [comment]
Mods that add new taxidermist recipes don't modify any files. Only add new file for every new item. So there should not be any conflict.

**Comment by warius1983** [comment]
finally some Good News! :D

**Comment by warius1983** [comment]
I saw you created badges and are the shards, can you summerize the rules where to get them? checking the files is a bit hard :P

**Comment by datchannin** [comment]
I've added badges to all location loot. Now change to get 1 badge is 10%.
Also I've added receipts for taxidermist:
![image](https://user-images.githubusercontent.com/39913306/97811012-d7685100-1c88-11eb-9e3a-77b03d4cffca.png)
10 badges + 20000 gold = armor token
8 badges + 18000 gold = helmet token
6 badges + 10000 gold = shoulder token
I don't know is it possible to get full set before day 90. Seems this is should be tested.

**Comment by warius1983** [comment]
Badges of Justice Revolution ahahahah! pretty neat indeed, ok everything is perfect a small extra feature, it may sound strange but do the badges have a semi nice vendor value?

**Comment by datchannin** [comment]
Now value is 2000 gold. But it can be changed later.

**Comment by warius1983** [comment]
so 10% to get a badge from any location...... Leave me some time to think and it comes from only Location Loot right? not form single enemies? even champion for sure do not drop right?

**Comment by datchannin** [comment]
Only locations. All types locations - orcs, goblin, undead and so on.

**Comment by warius1983** [comment]
mmm assuming you make a 1 location per day, 1,5 at most considering the delay you have at the beginning where you skipped them is definitevely not enough, you do 150 locations and maybe get25 badges at most, it's just one full tier set, or two pieces, probaly one confirmed badge per location will be fine.

I asked about the vendor price for this exact motivation, you may have plenty badges but no gold at also having badges is kinda useless if you don't have gold, so having multiple drop of badges may be useless if you can't combine them, if we assume that 3 brothers may be full gear by day 90, means you will need 24X3 badges, 72 and 48kX 3 gold, 141k gold.

Well on papers seems like having a set may be difficult under many aspects, I'd say 3 badges per location, and with a real sell value of 500 gold each, this way people can feel happy about getting them and exchange them for the gold required, they also take much room in inventory, so you can't stack so many of them.

I am pretty sure that gold will be the problem in the end, and until you have one limit badges are useless, so you can drop many and still have the situation in check, what do you say?

**Comment by warius1983** [comment]
let me test anyway, otherwise we reduce

**Comment by datchannin** [comment]
Firstly, 2000 gold for 1 badge is not does not mean you can sell it for 2000 gold. This is depends on reputation.
For example ~40 game day:
![image](https://user-images.githubusercontent.com/39913306/97816818-1f976b80-1ca9-11eb-9bb5-0fc68a56ac9b.png)

**Comment by datchannin** [comment]
I've test tonight some time farming only locations. And have 1 badge to day 34.
May be badge should be looted with 100% probability.
24 locations can be farmed before day 90.
Also you have not stop farm at day 90. You can do it until you decide to try attack gnolls.

**Comment by warius1983** [comment]
excellent, i wanted a sell value of that entity

**Comment by warius1983** [comment]
maybe in future we can have 100% loot chance, and depending by the loccation more badges maybe

**Comment by datchannin** [comment]
Loot chance for badge is 100% now.

**Comment by datchannin** [comment]
Closed. Taxidermist recipes T0 were added.
