### ISSUE TITLE
[Hunter] Handgonne perk damage fix

### ISSUE THREAD

**Issue by warius1983** [datchannin/Brothers-WoW#46]
function onUpdate( _properties )
	{
		_properties.IsMasterInCrossbow = true;
	}
	
	function onAnySkillUsed( _skill, _targetEntity, _properties )
	{
		local mainhand = this.getContainer().getActor().getItems().getItemAtSlot(this.Const.ItemSlot.Mainhand);
		if (mainhand != null && mainhand.isItemType(this.Const.Items.ItemType.RangedWeapon))
		{
			if (_skill.getID() == "actives.shoot_bolt" || _skill.getID() == "actives.shoot_stake")
			{
				_properties.DamageTotalMult *= 1.2;
			}
		}
	}
});

I may be wrong but 20% more damage on crossbow perk is not working with handgonne, mastery is working as BB intended

![image](https://user-images.githubusercontent.com/73758055/98108688-b6784980-1e9c-11eb-822a-2f11e4cd5c2a.png)

**Comment by datchannin** [comment]
This perk was created before handgonnes were added to game

**Comment by warius1983** [comment]
I know it was just not updated during Blazing Desert DLC

**Comment by datchannin** [comment]
Should be fixed in
https://github.com/datchannin/Brothers-WoW/commit/fc8639ea9396a5a8f751fbec6aa323b228b3533c
Need to been tested.

**Comment by warius1983** [comment]
I download and test it

**Comment by warius1983** [comment]
![image](https://user-images.githubusercontent.com/73758055/98116264-57203680-1ea8-11eb-8a45-27e259b78c46.png)

Ok working case closed!

**Comment by datchannin** [comment]
Thanks!
