### ISSUE TITLE
[Mage] PYROBLAST and FROST NOVA

### ISSUE THREAD

**Issue by warius1983** [datchannin/Brothers-WoW#48]
I have been trying these two spells, Man they rock, they are very good implementation, but I am assuming some values are still to be tuned I explain why.

Pyroblast ( no staff)
![image](https://user-images.githubusercontent.com/73758055/99917178-f51c5980-2d0e-11eb-83c5-627951c9bf7e.png)

Fireball (no staff)
![image](https://user-images.githubusercontent.com/73758055/99917191-07969300-2d0f-11eb-8780-4d8a9843f79c.png)

At the moment Pyroblast deal less damage then 3  pyroblasts, and cost more fatique, so I am asking why should I use it?
Is it supposed to do more damage than 3 fireballs casted on a single target at the same fatique? or is it supposed to do less damage than 3 fireball but cost less fatique? atm it makes no sense, but I am sure it's just a code implementation for now. It makes very sense that you have "to ignite" the target first however. Very cool effect

Frost Nova.
![image](https://user-images.githubusercontent.com/73758055/99917443-a1127480-2d10-11eb-842b-55204fc0911f.png)

Frost nova if I intended correctly, applies another freeze or is the same from perk T6?
I think it would be nice if it could inflict a slow like crippled ( +1 AP cost per tile of movement ) to the enemies already freezed by frost bolt hit with the AOE cast, a mass freeze like it is now is kinda too powerful, and most of all doesn't require the use of Winter chill. However everything can change by the AP that enemies have as default.

They are wonderful ideas, I just need to understand better what they do

**Comment by datchannin** [comment]
I've added these spells to create Fire Mage spec not the same as Frost. So Fire Mage is mostly for damage, Frost with Frost Nova should be used to control pack of enemies and less damage than Fire.
Pyroblast: damage is less than 3xFireballs. This happens because Fireball base power is increased from other perks (BlastWave) and from T0 Set. Pyroblast increase base power only from Fire Attunement. This should be balanced.
Frost Nova: applies the same freeze effect as from Winters Chill. May be this spell should be used only on target that is already freezed by Frostbolt. But this will be difficult to catch pack of enemies around of freezed one from previous turn.

**Comment by warius1983** [comment]
Ok I got good answers, so:

Pyroblast should be hyper ST nuke, and not it doesn't scale with all fire perks atm. ( to be fixed or change only base damage).

Frost nova: maybe should work on frozen targets by winterchill, if it is so, make a different debuff that that of winterchill.
or it could apply a base debuff as default ( +1AP per tile moved ) and if target was frozen some more debuff? 

Keep it up!!!!

**Comment by warius1983** [comment]
I was reading last fixes, and you added the base perk to pyroblast but shouldn't they be like X3 at least?
I beleive they should be X4 to give any sense it's like using 4X fireball in a single turn instead of three still the numbers are not working yet, but the raw implementations hould be correct

**Comment by datchannin** [comment]
Yes, spd addition used 3 times for Fireball and 1 time for Pyroblast.
I'll add new scale coeff to increase Pyroblast damage. This will balance base power.
Also I think should be added cooldown 1 turn at least to this spell.

**Comment by warius1983** [comment]
ok i gree but in the end if pyroblast does damage equal to 3X fireball why should I use it?
where is the gain to use it?

**Comment by datchannin** [comment]
pyroblast does more damage than 3x fireball, also it cheeper.

**Comment by warius1983** [comment]
OK now it is clear, knowing this I can valutate its effectiveness

**Comment by datchannin** [comment]
I've updated scale coeff and added cooldown.
I expected pyroblast will be equal or less than fireball if mage doed not have staff+tier set or when mage is low-leveled.
When mage has more level and more base spell power, damage should grow quickly.
What about Frost Nova.
use it only to frozen target is not OK, this is difficult to first use Frostbolt and expect to next turn that there will be circle of unfrozen enemies around of frozen one.
also set (+ fatigue cost movement) will create this spell useless if enemies already near your character and combat is in progress.
Need something else. May be add freeze effect to 7 targets/1 turn with Frost Nova and 1 target/3 turn with Frostbolt. For mass control/solo target control.

**Comment by warius1983** [comment]
I will check as soon you update all
